// Generated by tools/generate_model_catalog.mjs. Edit tools/model_router.js.
const modelMetadata = <Map<String,Object>>[
  {"id":"qwen-2.5-coder-0.5b","model":"Qwen 2.5 Coder 0.5B","size":"~1 GB working memory (estimate)","detail":"ONNX · weights downloaded on first use","quants":"Auto, Q4F16, Q4, Q8, FP16","tier":"Lite","web":true},
  {"id":"gemma-4-e2b","model":"Gemma 4 E2B","size":"~4 GB working memory (estimate)","detail":"ONNX · weights downloaded on first use","quants":"Auto, QAT / mobile-optimized, Q4F16, Q4, Q8, FP16","tier":"Vision","web":true},
  {"id":"gemma-4-e4b","model":"Gemma 4 E4B","size":"~8 GB working memory (estimate)","detail":"ONNX · weights downloaded on first use","quants":"Auto, QAT / mobile-optimized, Q4F16, Q4, Q8, FP16","tier":"Smart","web":true},
  {"id":"spark-x2.5-1.7b","model":"Spark-X2.5 1.7B","size":"Build unavailable","detail":"litert · compatible backend not installed","quants":"Auto","tier":"Lite","web":false},
  {"id":"spark-x2.5-4b","model":"Spark-X2.5 4B","size":"Build unavailable","detail":"litert · compatible backend not installed","quants":"Auto","tier":"Smart","web":false},
  {"id":"ternary-bonsai-2-27b","model":"Ternary Bonsai 2 27B","size":"Build unavailable","detail":"gguf · compatible backend not installed","quants":"Auto","tier":"Ultra","web":false},
];
const modelQuantizations = <String,List<String>>{
  "qwen-2.5-coder-0.5b": ["Auto","Q4F16","Q4","Q8","FP16"],
  "gemma-4-e2b": ["Auto","QAT / mobile-optimized","Q4F16","Q4","Q8","FP16"],
  "gemma-4-e4b": ["Auto","QAT / mobile-optimized","Q4F16","Q4","Q8","FP16"],
  "spark-x2.5-1.7b": ["Auto"],
  "spark-x2.5-4b": ["Auto"],
  "ternary-bonsai-2-27b": ["Auto"],
};
List<String> quantizationsFor(String model) => modelQuantizations[model] ?? const ['Auto','Q4F16','Q4','Q8','FP16'];
