import {writeFileSync} from 'node:fs';
import {modelProfiles,quantizationsFor} from './model_router.js';
const quote=value=>JSON.stringify(value).replace(/\$/g,'\\$');
const rows=Object.entries(modelProfiles).map(([id,p])=>{
  const values={id,model:p.label,size:p.estimatedWorkingGB?`~${p.estimatedWorkingGB} GB working memory (estimate)`:'Build unavailable',detail:p.runtime==='transformers'?'ONNX · weights downloaded on first use':`${p.runtime} · compatible backend not installed`,quants:quantizationsFor(id).join(', '),tier:p.tier,web:p.runtime==='transformers'};
  return `  {${Object.entries(values).map(([k,v])=>`${quote(k)}:${typeof v==='boolean'?v:quote(v)}`).join(',')}},`;
});
const quants=Object.keys(modelProfiles).map(id=>`  ${quote(id)}: ${JSON.stringify(quantizationsFor(id))},`).join('\n');
writeFileSync(new URL('../lib/features/ai/model_catalog.g.dart',import.meta.url),`// Generated by tools/generate_model_catalog.mjs. Edit tools/model_router.js.\nconst modelMetadata = <Map<String,Object>>[\n${rows.join('\n')}\n];\nconst modelQuantizations = <String,List<String>>{\n${quants}\n};\nList<String> quantizationsFor(String model) => modelQuantizations[model] ?? const ['Auto','Q4F16','Q4','Q8','FP16'];\n`);
